### PR TITLE
Update initialize function name

### PR DESCRIPTION
**Pull request by johnpeck-us-ibm**
Updates the initialize function to include package name to be unique. Other functions look to be okay and not likely for a collision.

Tested winx64

Fixes: https://github.com/IBM/OpenJCEPlus/issues/76

Signed-off-by: John Peck <johnpeck@us.ibm.com>

### CODE REVIEW

**Comment by KostasTsiounis** [comment]
I think we should put the `Fixes: https://github.com/IBM/OpenJCEPlus/issues/76` in the description, instead of the title of the PR.

**Comment by jasonkatonica** [comment]
x86_64_linux

**Comment by johnpeck-us-ibm** [comment]
> I think we should put the `Fixes: https://github.com/IBM/OpenJCEPlus/issues/76` in the description, instead of the title of the PR.

Hi Kostas,
Lets do the following: Add the issue number to the title of the PR, but the link into the description and link the PR to the issue. This way it is easy to find the related 76 for a PR and if someone for forgets one of the above. At least we have the others. Also, with the issue number in the PR it is easy to find related PR when looking for support issues etc.

**Comment by mstoodle** [comment]
I'll lob in a comment from the sidelines :) : the issue already gets a comment added with a link to any commit with the Fixes: line in the description once the commit is added to a branch or merged. That seems like the most convenient way to connect issues to code changes, so long as contributors/reviewers are diligent about making sure the Fixes: line is there.

**Comment by KostasTsiounis** [comment]
Mark is right. Once we add the `Fixes:` line, a link to the PR is created automatically like a comment. Thus, you can always search the issues, find the one you want and go to the associated PR. So, there is no need for a manual link on the issue side. We usually don't include the issue number in the PR title, since you can get there through the actual issue, but I'm OK if you want to keep it there.

**Comment by johnpeck-us-ibm** [comment]
That works for me.

**Review by KostasTsiounis — APPROVED** [review]
LGTM

**Review by jasonkatonica — APPROVED** [review]
LGTM

**Pull request merged**
