### PR TITLE
Update the README.md file for the use of AI generated code.

### LINKED ISSUE #384: With the  use of AI code generation tools becoming more wide spread. Need to add an AI gen policy to the readme.
Update the README.md to contain a AI code generation policy.

### PR DESCRIPTION
**Pull request by johnpeck-us-ibm**
Fixes #384
Signed-off-by: John Peck <140550562+johnpeck-us-ibm@users.noreply.github.com>

### CODE REVIEW

**Review by jasonkatonica — APPROVED** [review]
LGTM

**Review by KostasTsiounis — APPROVED** [review]
LGTM

**Comment by KostasTsiounis** [comment]
@johnpeck-us-ibm @jasonkatonica Should we cherry-pick this to `java24` as well?

**Comment by jasonkatonica** [comment]
> @johnpeck-us-ibm @jasonkatonica Should we cherry-pick this to `java24` as well?

The code split occurred after this update was merged into main branch. I double checked and it is already inclluded in the `java24` branch so should be ok. https://github.com/IBM/OpenJCEPlus/commits/java24/

This being said all commits from this point forward made to `main` branch now have to be ported to the `java24` branch.

**Pull request merged**
